version: '3.1'

services:

  wordpress:
    build:
      context: app
      dockerfile: app/app.docker
    restart: always
    volumes:
      - ./app/src:/var/www/html
    ports:
      - 8084:80
    environment:
      APP_DB_PASSWORD: mrt
      APP_DB_NAME: mrt
      APP_DB_USER: mrt
      APP_DB_HOST: db

  db:
    build:
      context: db
      dockerfile: db/db.docker
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_DB: mrt
      POSTGRES_USER: mrt
      POSTGRES_PASSWORD: mrt

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

