# docker-compose for setup develop environment quick
version: '3.1'

services:
  backend:
    build:
      context: backend
      dockerfile: backend.docker
    restart: always
    depends_on:
      - "db"
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - 8000:8000
    environment:
      APP_DB_PASSWORD: mrt
      APP_DB_NAME: mrt
      APP_DB_USER: mrt
      APP_DB_HOST: db

  frontend:
    image: nginx:stable
    restart: always
    depends_on:
      - "backend"
    volumes:
      - ./frontend/build:/var/www/html
      - ./frontend/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  db:
    build:
      context: db
      dockerfile: db.docker
    volumes:
      - ./db/data:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      POSTGRES_DB: mrt
      POSTGRES_USER: mrt
      POSTGRES_PASSWORD: mrt
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    depends_on:
      - "db"
    ports:
    - 8081:8080

