# docker-compose for setup develop environment quick
version: '3.1'

services:
  backend:
    build:
      context: backend
      dockerfile: backend/backend.docker
    restart: always
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - 8000:8000
    environment:
      APP_DB_PASSWORD: mrt
      APP_DB_NAME: mrt
      APP_DB_USER: mrt
      APP_DB_HOST: db

  frontend:
    image: nginx:stable
    restart: always
    volumes:
      - ./frontend/build:/var/www/html
      - ./frontend/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  db:
    build:
      context: db
      dockerfile: db/db.docker
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_DB: mrt
      POSTGRES_USER: mrt
      POSTGRES_PASSWORD: mrt

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

