version: '3.1'
services:
  jenkins:
    image: jenkinsci/blueocean
    ports: 
      - "8000:8080"
    environment: 
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client:ro
    depends_on: 
      - docker

  docker:
    image: docker:dind
    privileged: true
    environment: 
      DOCKER_TLC_CERTDIR: /certs
    volumes: 
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client
      - docker-data:/var/lib/docker

volumes: 
  jenkins-data:
  docker-certs:
  docker-data: